title: 'hub.lol'
baseURL: 'https://hub.lol/'
languageCode: 'en-us'

rssLimit: 8

imaging:
  exif:
    disableDate: true
    disableLatLong: true

markup:
  highlight:
    style: 'bw'
    tabWidth: 4

permalinks:
  posts: "/:year/:month/:day/:slug/"

menu:
  main:
    - name: 'About'
      url: '/'
      weight: 1
    - name: 'Ramblings'
      url: '/posts/'
      weight: 2
#    - name: 'Projects'
#      url: '/projects/'
#      weight: 3
    - name: 'Reads'
      url: '/reads/'
      weight: 4
    - name: 'Honks'
      url: 'https://honks.hub.lol/'
      weight: 5

privacy:
  twitter:
    enableDNT: true
    simple: true
  vimeo:
    enableDNT: true
  youtube:
    privacyEnhanced: true
