name: '🧑‍🏭'
on: [ push ]
jobs:
  ci:
    permissions:
      id-token: write
      deployments: write
    runs-on: ubuntu-latest
    steps:

      - name: 'Fetch latest commit'
        uses: actions/checkout@v2.5.0

      - name: 'Install Nix'
        uses: cachix/install-nix-action@v18
        with:
          nix_path: "nixpkgs=channel:nixos-22.05"

      - name: 'Activate Nix store cache'
        uses: actions/cache@v3.0.11
        id: nix-cache
        with:
          path: "/tmp/nixcache"
          key: "nix-store-${{ hashFiles(format('{0}/shell.nix', github.workspace)) }}"

      - name: "Import Nix store cache"
        run: "nix-store --import < /tmp/nixcache"
        if: "steps.nix-cache.outputs.cache-hit == 'true'"

      - name: 'Build website'
        run: |
          nix-shell --run "make"

      - name: "Export Nix store cache"
        if: "steps.nix-cache.outputs.cache-hit != 'true'"
        run: "nix-store --export $(find /nix/store -maxdepth 1 -name '*-*') > /tmp/nixcache"

      - name: 'Publish to Cloudflare Pages'
        uses: cloudflare/pages-action@v1.1.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "nothub"
          directory: "public/"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Docker Hub login'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 'Publish to Docker Hub'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/website:latest
